version: "3"

services:
  web:
    container_name: sudoku-api
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: sdatabase
    image: mongo
    ports: 
      - "27017:27017"
